apiVersion: v1
version: 0.1.0
appVersion: latest
name: besu-node
description: Besu nodes for a POA network using IBFT2 for consensys
keywords:
  - ethereum
  - besu
  - hyperledger
  - enterprise
  - blockchain
  - pegasys
  - consensys
home: https://besu.hyperledger.org
sources:
  - https://github.com/hyperledger/besu
maintainers:
  - name: devops
    email: devops@pegasys.tech
icon: http://besu.hyperledger.org/en/latest/favicon.ico

