---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout.fullname" . }}
  labels:
    app: {{ template "blockscout.fullname" . }}
    chart: {{ template "blockscout.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ include "blockscout.fullname" . }}
    helm.sh/chart: {{ include "blockscout.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "blockscout.fullname" . }}
    release: {{ .Release.Name }}
    component: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "blockscout.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
      
