---
image:
  besu:
    repository: hyperledger/besu
    tag: latest
    pullPolicy: IfNotPresent
  orion:
    repository: consensys/quorum-orion
    tag: latest
    pullPolicy: IfNotPresent

nodeFlags:
  bootnode: false
  generateKeys: false
  privacy: false
  # be careful with this one
  removeKeysOnDeletion: false

node:
  # privKey:
  # pubKey:
  storage:
    enabled: true
    pvcSizeLimit: "10Gi"
    pvcStorageClass: "standard"
  resources:
    memRequest: "1024Mi"
    memLimit: "2048Mi"
    cpuRequest: "100m"
    cpuLimit: "500m"
  dataPath: "/data"
  genesisFilePath: "/etc/genesis/genesis.json"
  logging: INFO
  p2p:
    enabled: true
    host: "0.0.0.0"
    port: 30303
    discovery: true
    maxPeers: 25
  rpc:
    enabled: true
    host: "0.0.0.0"
    port: 8545
    api: '["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET"]'
    corsOrigins: '["all"]'
    authenticationEnabled: false
  ws:
    enabled: false
    host: "0.0.0.0"
    port: 8546
    api: '["DEBUG", "ETH", "WEB3", "NET"]'
    authenticationEnabled: false
  graphql:
    enabled: false
    host: "0.0.0.0"
    port: 8547
    corsOrigins: '["all"]'
  txPool:
    retentionHours: 999
    maxSize: 1024
  http:
    allowlist: '["*"]'
  metrics:
    enabled: true
    host: "0.0.0.0"
    port: 9545
  metricsPush:
    enabled: false
    host: "5.5.5.5"
    port: 9091
    interval: 15
    prometheusJob: "besu"
  privacy:
    enabled: false
    url: "http://127.0.0.1:8888"
    precompiledAddress: 9
  permissions:
    enabled: false
    nodes:
      enabled: false
      allowlist: ["enode://abcd..@1.2.3.3:30303","enode://efba..@1.2.3.4:besu-node-bootnode-1-0.besu-node-bootnode-1.besu.svc.cluster.local:30303"]
    nodesContract:
      enabled: false
      address: "0x0000000000000000000000000000000000001234"
    accounts:
      enabled: false
      allowlist: ["0x0000000000000000000000000000000000000009"]

privacy:
  # privKey:
  # pubKey:
  # password:
  # the orion bootnode so to speak
  othernodes: "self"
  orionConfig:
    nodeport: 8080
    nodenetworkinterface: "0.0.0.0"
    clientport: 8888
    clientnetworkinterface: "0.0.0.0"


nodeSelector: {}
tolerations: []
affinity: {}
resources: {}

ingress_http:
  enabled: false
  annotations: {}
  #   ingress.kubernetes.io/ssl-redirect: "false"

  # path: /
  # hosts:
  #   - k8s.localhost.lan
  # tls:
  #  - secretName: clique-tls
  #    hosts:
  #      - chain.apps.consensys

ingress_ws:
  enabled: false
  annotations: {}
