{{- if and .Values.bootnode.enabled .Values.bootnode.privKey -}}
{{- $fullname := (include "besu-node.fullname" .) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "besu-node.fullname" . }}-keys
  labels:
    app.kubernetes.io/name: {{ include "besu-node.name" . }}-keys
    helm.sh/chart: {{ include "besu-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  private.key: |-
    {{ .Values.bootnode.privKey | b64enc }}

{{- end -}}