---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu-node.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "besu-node.name" . }}
    helm.sh/chart: {{ include "besu-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: json-rpc
      port: {{ .Values.node.rpc.port }}
      targetPort: json-rpc
    - name: ws
      port: {{ .Values.node.ws.port }}
      targetPort: ws
    - name: graphql
      port: {{ .Values.node.graphql.port }}
      targetPort: graphql
    - name: rlpx
      port: {{ .Values.node.p2p.port }}
      targetPort: rlpx
      protocol: TCP
    - name: discovery
      port: {{ .Values.node.p2p.port }}
      targetPort: discovery
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "besu-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
