---

nodeFlags:
  bootnode: true
  generateKeys: false
  privacy: false
  removeKeysOnDeletion: false

node:
  besu:
    metrics:
      serviceMonitorEnabled: false  

cloudSecretsStore: false
provider: local