---
nodeFlags:
  bootnode: false
  generateKeys: false
  privacy: false
  removeKeysOnDeletion: false

node:
  besu:
    metrics:
      serviceMonitorEnabled: true
  goquorum:
    metrics:
      serviceMonitorEnabled: true          

cloudSecretsStore: false
provider: local