
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "goquorum-node.fullname" . }}
  labels:
    app: {{ template "goquorum-node.fullname" . }}
    chart: {{ template "goquorum-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    helm.sh/chart: {{ include "goquorum-node.chart" . }}
    app.kubernetes.io/name: {{ include "goquorum-node.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "goquorum-node.fullname" . }}
    release: {{ .Release.Name }}
    component: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "goquorum-node.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: json-rpc
      port: {{ .Values.node.goquorum.rpc.port }}
      targetPort: json-rpc
      protocol: TCP
    - name: ws
      port: {{ .Values.node.goquorum.ws.port }}
      targetPort: ws
      protocol: TCP
    - name: graphql
      port: {{ .Values.node.goquorum.graphql.port }}
      targetPort: graphql
      protocol: TCP
    - name: rlpx
      port: {{ .Values.node.goquorum.p2p.port }}
      targetPort: rlpx
      protocol: TCP
    - name: discovery
      port: {{ .Values.node.goquorum.p2p.port }}
      targetPort: discovery
      protocol: UDP
    - name: metrics
      port: {{ .Values.node.goquorum.metrics.pprofport }}
      targetPort: metrics
      protocol: TCP

{{- if .Values.quorumFlags.privacy }}
    - name: tessera
      port: {{ .Values.node.tessera.port }}
      targetPort: tessera
      protocol: TCP
    - name: tessera-tp
      port: {{ .Values.node.tessera.tpport }}
      targetPort: tessera-tp
      protocol: TCP
    - name: tessera-q2t
      port: {{ .Values.node.tessera.q2tport }}
      targetPort: tessera-q2t
      protocol: TCP
{{- end }}
