
{{- if and .Values.node.goquorum.metrics.enabled .Values.node.goquorum.metrics.serviceMonitorEnabled }}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "goquorum-node.fullname" . }}-servicemonitor
  labels:
    release: monitoring
    app.kubernetes.io/name: {{ include "goquorum-node.fullname" . }}
    app.kubernetes.io/part-of: {{ include "goquorum-node.fullname" . }}
    app.kubernetes.io/namespace: {{ template "goquorum-node.chart" . }}
    app.kubernetes.io/release: monitoring
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "goquorum-node.fullname" . }}
      app.kubernetes.io/part-of: {{ include "goquorum-node.fullname" . }}
      app.kubernetes.io/namespace: {{ .Release.Namespace }}
      app.kubernetes.io/release: {{ .Release.Name }}
  endpoints:
  - port: metrics
    interval: 15s
    path: /debug/metrics/prometheus
    scheme: http
    honorLabels: true
{{- end }}

