---
apiVersion: 1
deleteDatasources:
  - name: Graphite
    orgId: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://$PROMETHEUS_SERVICE_HOST.monitoring:9090
    password:
    user:
    database:
    basicAuth:
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:
      tlsCACert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
      password:
      basicAuthPassword:
    version: 1
    editable: true