{{- if .Values.node.privkey -}}
{{- $fullname := (include "besu-node.fullname" .) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "besu-node.fullname" . }}-validators
  labels:
    app.kubernetes.io/name: {{ include "besu-node.name" . }}-validators
    helm.sh/chart: {{ include "besu-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  private.key: |-
    {{ .Values.node.privkey | b64enc }}
  public.key: |-
    {{ .Values.node.pubkey | b64enc }}

  {{ if regexMatch "^0x" .Values.node.pubkey }}
  enode.key: {{ trimPrefix "0x" .Values.node.pubkey | quote }}
  {{ else }}
  enode.key: {{ .Values.node.pubkey | quote }}
  {{ end }}


{{- end -}}