{{- if .Values.ingress_ws.enabled -}}
{{- $fullName := include "besu-node.fullname" . -}}
{{- $ingressPath := .Values.ingress_ws.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ws
  labels:
    app: {{ include "besu-node.name" . }}
    chart: {{ include "besu-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress_ws.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress_ws.tls }}
  tls:
  {{- range .Values.ingress_ws.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress_ws.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: ws
  {{- end }}
{{- end }}
