# Default values for besu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imagePullPolicy: IfNotPresent
image:
  repository: hyperledger/besu
  tag: latest

namespace: besu

bootnode1:
  privateKey: "0x3262e00fd76fdb2cbec12ff964b288255846446be6950d5f0519b77dcdbea98d"
  publicKey: "0xaeb7f4753d5ac9be20cb98489b90857e70ca5db97b95b1c4099e61ff4d920e671095696db6c44acf0fb8321d151480438c6e696236b5d88a19b2d83ccd7a2a21"

bootnode2:
  privateKey: "0xbcf83add2e46f8ed4680ba146d4d8558480400fd24e62052e17f21e41e376732"
  publicKey: "0x5b80b7aded4d9e91b1fb8db7e7e16b136d0e49af295ef8a572b42ebb88e3996b8704585ff63f1adfc7cd945aef4ab94a161c49201b7346a237a764106444c7a8"

node:
  replicaCount: 2
  pvcSizeLimit: "1Gi"
  pvcStorageClass: "standard"
  memRequest: "1024Mi"
  memLimit: "2048Mi"
  cpuRequest: "100m"
  cpuLimit: "500m"

# common parameters to all nodes
besuConfig:
  dataPath: "/data"
  genesisFilePath: "/etc/genesis/genesis.json"
  logging: INFO
  p2p:
    enabled: true
    host: "0.0.0.0"
    port: 30303
    discovery: true
    maxPeers: 25
  rpc:
    enabled: true
    host: "0.0.0.0"
    port: 8545
    api: '["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET"]'
    corsOrigins: '["all"]'
    authenticationEnabled: false
  ws:
    enabled: false
    host: "0.0.0.0"
    port: 8546
    api: '["DEBUG", "ETH", "WEB3", "NET"]'
    authenticationEnabled: false
  graphql:
    enabled: false
    host: "0.0.0.0"
    port: 8547
    corsOrigins: '["all"]'
  txPool:
    retentionHours: 999
    maxSize: 1024
  http:
    allowlist: '["*"]'
  metrics:
    enabled: true
    host: "0.0.0.0"
    port: 9545
  metricsPush:
    enabled: false
    host: "5.5.5.5"
    port: 9091
    interval: 15
    prometheusJob: "besu"
  privacy:
    enabled: false
    url: "http://127.0.0.1:8888"
    precompiledAddress: 9
  permissions:
    enabled: false
    nodes:
      enabled: false
      filePath: "/etc/permissions"
    nodesContract:
      enabled: false
      address: "0x0000000000000000000000000000000000001234"
    accounts:
      enabled: false
  miner:
    enabled: true
    coinbase: "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
    extra_data: "0x444F4E27542050414E4943202120484F444C2C20484F444C2C20484F444C2021"
    gas_price: "0"