apiVersion: v1
kind: Service
metadata:
  name: cakeshop
  labels:
    app: cakeshop
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: cakeshop
  ports:
    - port: 8999
      targetPort: 8999
      nodePort: 30099
      protocol: TCP
      name: cakeshop
