---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "besu-genesis.fullname" . }}-role
  labels:
    app.kubernetes.io/name: {{ include "besu-genesis.name" . }}
    helm.sh/chart: {{ include "besu-genesis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - update
      - patch
      - create
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "besu-genesis.fullname" . }}-role-binding
  labels:
    app.kubernetes.io/name: {{ include "besu-genesis.name" . }}
    helm.sh/chart: {{ include "besu-genesis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: genesis-besu-genesis-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}

