{{- if and (eq .Values.cluster.provider "aws") (.Values.cluster.cloudNativeServices) }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "besu-node.fullname" . }}-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects:  |
        - objectName: {{ include "besu-node.fullname" . }}-nodekey
          objectAlias: nodekey
          objectType: secretsmanager
          objectVersion: ""
        - objectName: {{ include "besu-node.fullname" . }}-nodekeypub
          objectAlias: nodekey.pub
          objectType: secretsmanager
          objectVersion: ""
        - objectName: {{ include "besu-node.fullname" . }}-enode
          objectAlias: enode
          objectType: secretsmanager
          objectVersion: ""
      {{- if .Values.quorumFlags.privacy }}
        - objectName: {{ include "besu-node.fullname" . }}-tmkey
          objectAlias: tm.key
          objectType: secretsmanager
          objectVersion: ""
        - objectName: {{ include "besu-node.fullname" . }}-tmkeypub
          objectAlias: tm.pub
          objectType: secretsmanager
          objectVersion: ""
        - objectName: {{ include "besu-node.fullname" . }}-tmpassword
          objectAlias: tm.password
          objectType: secretsmanager
          objectVersion: ""
      {{- end }}
{{- end }}