{{- if eq .Values.cluster.provider "azure" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000
  - mfsymlinks
parameters:
  skuName: Standard_LRS

{{- else if eq .Values.cluster.provider "aws" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: gp3
  fsType: ext4

# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: {{ include "besu-node.fullname" . }}-storage
#   namespace: {{ .Release.Namespace }}
# provisioner: efs.csi.aws.com
# reclaimPolicy: Retain
# parameters:
#   provisioningMode: efs-ap
#   fileSystemId: #your_file_system_id
#   directoryPerms: "700"
#   gidRangeStart: "1000" # optional
#   gidRangeEnd: "2000" # optional
#   basePath: "/dynamic_provisioning" # optional

{{- else }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "besu-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: {{ include "besu-node.fullname" . }}-storage
  capacity:
    storage: "{{ .Values.storage.sizeLimit }}"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/{{ include "besu-node.fullname" . }}"

{{- end }}

{{- if eq .Values.cluster.provider "local" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "besu-node.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ include "besu-node.fullname" . }}-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.storage.pvcSizeLimit }}"
{{- end }}