---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "quorum-monitoring.fullname" . }}-grafana
  labels:
    app: {{ template "quorum-monitoring.name" . }}
    chart: {{ template "quorum-monitoring.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
    component: grafana
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grafana
  template:
    metadata:
      labels:
        app: {{ template "quorum-monitoring.name" . }}
        release: {{ .Release.Name }}
        component: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.image.grafana.repository }}:{{ .Values.image.grafana.tag }}
          imagePullPolicy: {{ .Values.image.grafana.pullPolicy }}
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.username }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.password }}
            - name: PROMETHEUS_SERVICE_HOST
              value: {{ template "quorum-monitoring.fullname" . }}-prometheus
            - name: PROMETHEUS_NAMESPACE
              value: {{ .Release.Namespace }}
          volumeMounts:
            - name: grafana-cm-datasources
              mountPath: /etc/grafana/provisioning/datasources/prometheus.yml
              subPath: prometheus.yml
              readOnly: true
            - name: grafana-cm-dash-default
              mountPath: /etc/grafana/provisioning/dashboards/dashboard.yml
              subPath: dashboard.yml
              readOnly: true
            - name: grafana-cm-dash-goquorum
              mountPath: /etc/grafana/provisioning/dashboards/goquorum.json
              subPath: goquorum.json
              readOnly: true
            - name: grafana-cm-dash-besu
              mountPath: /etc/grafana/provisioning/dashboards/besu.json
              subPath: besu.json
              readOnly: true
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
      volumes:
        - name: grafana-cm-datasources
          configMap:
            name: {{ template "quorum-monitoring.fullname" . }}-grafana-cm-datasources
        - name: grafana-cm-dash-default
          configMap:
            name: {{ template "quorum-monitoring.fullname" . }}-grafana-cm-dash-default
        - name: grafana-cm-dash-goquorum
          configMap:
            name: {{ template "quorum-monitoring.fullname" . }}-grafana-cm-dash-goquorum
        - name: grafana-cm-dash-besu
          configMap:
            name: {{ template "quorum-monitoring.fullname" . }}-grafana-cm-dash-besu
