---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blockscout.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "blockscout.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "blockscout.fullname" . }}-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "blockscout.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "blockscout.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "blockscout.fullname" . }}
  labels:
    app: {{ template "blockscout.fullname" . }}
    chart: {{ template "blockscout.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    component: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "blockscout.fullname" . }}
    helm.sh/chart: {{ include "blockscout.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: {{ template "blockscout.fullname" . }}
      release: {{ .Release.Name }}
      component: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "blockscout.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "blockscout.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "blockscout.fullname" . }}
        release: {{ .Release.Name }}
        component: {{ .Release.Name }}
        app.kubernetes.io/name: {{ include "blockscout.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "blockscout.fullname" . }}-sa
      containers:

      - name: {{ .Release.Name }}-blockscout
        image: {{ .Values.image.blockscout.repository }}:{{ .Values.image.blockscout.tag }}
        imagePullPolicy: {{ .Values.image.blockscout.pullPolicy }}
        resources:
          requests:
            cpu: "{{ .Values.blockscout.resources.cpuRequest }}"
            memory: "{{ .Values.blockscout.resources.memRequest }}"
          limits:
            cpu: "{{ .Values.blockscout.resources.cpuLimit }}"
            memory: "{{ .Values.blockscout.resources.memLimit }}"
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PORT
            value: {{ .Values.blockscout.port | quote }}
          - name: DATABASE_URL
            value: {{ .Values.blockscout.database_url }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.blockscout.postgres_password }}
          - name: POSTGRES_USER
            value: {{ .Values.blockscout.postgres_user }}
          - name: NETWORK
            value: {{ .Values.blockscout.network }}
          - name: SUBNETWORK
            value: {{ .Values.blockscout.subnetwork }}
          - name: CHAIN_ID
            value: {{ .Values.blockscout.chain_id | quote }}
          - name: COIN
            value: {{ .Values.blockscout.coin }}
          - name: ETHEREUM_JSONRPC_VARIANT
            value: {{ .Values.blockscout.ethereum_jsonrpc_variant }}
          - name: ETHEREUM_JSONRPC_TRANSPORT
            value: {{ .Values.blockscout.ethereum_jsonrpc_transport }}
          - name: ETHEREUM_JSONRPC_HTTP_URL
            value: http://{{ .Values.blockscout.ethereum_jsonrpc_endpoint }}:8545
          - name: ETHEREUM_JSONRPC_TRACE_URL
            value: http://{{ .Values.blockscout.ethereum_jsonrpc_endpoint }}:8545
          - name: ETHEREUM_JSONRPC_WS_URL
            value: ws://{{ .Values.blockscout.ethereum_jsonrpc_endpoint }}:8546
          - name: SECRET_KEY_BASE
            value: {{ .Values.blockscout.secret_key_base }}        
        ports:
          - name: http
            containerPort: {{ .Values.blockscout.port }}
            protocol: TCP
        command:
          - /bin/sh
          - -c
        args:
          - |
            exec
            cd /opt/app/ && echo $$MIX_ENV && mix do ecto.create, ecto.migrate; mix phx.server;