---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockscout.fullname" . }}
  labels:
    app.kubernetes.io/name: blockscout
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ include "blockscout.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ include "blockscout.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
      
