{{- $memberNumber := "member2" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "besu.fullname" . }}-{{ $memberNumber }}
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ $memberNumber }}
    namespace: {{ .Values.namespace }}
    app.kubernetes.io/name: besu
    app.kubernetes.io/release: "1.0.0"
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "besu.name" . }}
    release: {{ .Release.Name }}
    component: {{ $memberNumber }}
  ports:
    - name: json-rpc
      port: {{ .Values.besuConfig.rpc.port }}
      targetPort: json-rpc
      protocol: TCP
    - name: ws
      port: {{ .Values.besuConfig.ws.port }}
      targetPort: ws
      protocol: TCP
    - name: graphql
      port: {{ .Values.besuConfig.graphql.port }}
      targetPort: graphql
      protocol: TCP
    - name: rlpx
      port: {{ .Values.besuConfig.p2p.port }}
      targetPort: rlpx
      protocol: TCP
    - name: discovery
      port: {{ .Values.besuConfig.p2p.port }}
      targetPort: discovery
      protocol: UDP
    - port: {{ .Values.tesseraConfig.port }}
      targetPort: {{ .Values.tesseraConfig.port }}
      protocol: TCP
      name: tessera
    - port: {{ .Values.tesseraConfig.tpPort }}
      targetPort: {{ .Values.tesseraConfig.tpPort }}
      protocol: TCP
      name: tessera-tp
    - port: {{ .Values.tesseraConfig.q2tPort }}
      targetPort: {{ .Values.tesseraConfig.q2tPort }}
      protocol: TCP
      name: tessera-q2t      

