apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "besu.fullname" . }}-genesis-configmap
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
data:
  genesis.json: |-
{{ .Files.Get "genesis.json" | indent 4}}



