---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "besu-genesis.fullname" . }}-tls-secret
  labels:
    app: {{ template "besu-genesis.name" . }}
    chart: {{ template "besu-genesis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ include "besu-genesis.name" . }}
    helm.sh/chart: {{ include "besu-genesis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  bootnode-1-nodekey: |-
{{ .Files.Get "bootnode-1-nodekey" | b64enc |indent 4 }}

  bootnode-1-nodekey.pub: |-
{{ .Files.Get "bootnode-1-nodekey.pub" | b64enc |indent 4 }}

  bootnode-1-address: |-
{{ .Files.Get "bootnode-1-address" | b64enc |indent 4 }}

  bootnode-2-nodekey: |-
{{ .Files.Get "bootnode-2-nodekey" | b64enc |indent 4 }}

  bootnode-2-nodekey.pub: |-
{{ .Files.Get "bootnode-2-nodekey.pub" | b64enc |indent 4 }}

  bootnode-2-address: |-
{{ .Files.Get "bootnode-2-address" | b64enc |indent 4 }}

  rpc-1-nodekey: |-
{{ .Files.Get "rpc-1-nodekey" | b64enc |indent 4 }}

  rpc-1-nodekey.pub: |-
{{ .Files.Get "rpc-1-nodekey.pub" | b64enc |indent 4 }}

  rpc-1-address: |-
{{ .Files.Get "rpc-1-address" | b64enc |indent 4 }}

  rpc-2-nodekey: |-
{{ .Files.Get "rpc-2-nodekey" | b64enc |indent 4 }}

  rpc-2-nodekey.pub: |-
{{ .Files.Get "rpc-2-nodekey.pub" | b64enc |indent 4 }}

  rpc-2-address: |-
{{ .Files.Get "rpc-2-address" | b64enc |indent 4 }}

  truststore.jks: |-
{{ .Files.Get "truststore.jks" | b64enc |indent 4 }}

  jkspassword.txt: |-
{{ .Files.Get "jkspassword.txt" | b64enc |indent 4 }}

  bootnode-1.jks: |-
{{ .Files.Get "bootnode-1.jks" | b64enc |indent 4 }}

  bootnode-1.pem: |-
{{ .Files.Get "bootnode-1.pem" | b64enc |indent 4 }}

  bootnode-2.jks: |-
{{ .Files.Get "bootnode-2.jks" | b64enc |indent 4 }}

  bootnode-2.pem: |-
{{ .Files.Get "bootnode-2.pem" | b64enc |indent 4 }}

  rpc-1.jks: |-
{{ .Files.Get "rpc-1.jks" | b64enc |indent 4 }}

  rpc-1.pem: |-
{{ .Files.Get "rpc-1.pem" | b64enc |indent 4 }}

  rpc-2.jks: |-
{{ .Files.Get "rpc-2.jks" | b64enc |indent 4 }}

  rpc-2.pem: |-
{{ .Files.Get "rpc-2.pem" | b64enc |indent 4 }}

  validator-1.jks: |-
{{ .Files.Get "validator-1.jks" | b64enc |indent 4 }}

  validator-1.pem: |-
{{ .Files.Get "validator-1.pem" | b64enc |indent 4 }}

  validator-2.jks: |-
{{ .Files.Get "validator-2.jks" | b64enc |indent 4 }}

  validator-2.pem: |-
{{ .Files.Get "validator-2.pem" | b64enc |indent 4 }}

  validator-3.jks: |-
{{ .Files.Get "validator-3.jks" | b64enc |indent 4 }}

  validator-3.pem: |-
{{ .Files.Get "validator-3.pem" | b64enc |indent 4 }}

  validator-4.jks: |-
{{ .Files.Get "validator-4.jks" | b64enc |indent 4 }}

  validator-4.pem: |-
{{ .Files.Get "validator-4.pem" | b64enc |indent 4 }}
