apiVersion: v1
kind: Service
metadata:
  name: besu-member2
  labels:
    app: member2
  namespace: besu
spec:
  type: ClusterIP
  selector:
    app: member2
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: discovery
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: rlpx
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: json-rpc
    - port: 8546
      targetPort: 8546
      protocol: TCP
      name: ws
    - port: 8547
      targetPort: 8547
      protocol: TCP
      name: graphql
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: tessera
    - port: 9080
      targetPort: 9080
      protocol: TCP
      name: tessera-tp
    - port: 9101
      targetPort: 9101
      protocol: TCP
      name: tessera-q2t      
      