---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goquorum-genesis.name" . }}-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "goquorum-genesis.name" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "goquorum-genesis.name" . }}
    helm.sh/chart: {{ include "goquorum-genesis.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create", "get", "list", "update", "delete" ]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "goquorum-genesis.name" . }}-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "goquorum-genesis.name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "goquorum-genesis.name" . }}-sa
    namespace: {{ .Release.Namespace }}


---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "goquorum-genesis.name" . }}-init
  labels:
    aadpodidbinding: "{{ .Values.azure.identityName }}"
    app: {{ template "goquorum-genesis.name" . }}
    chart: {{ template "goquorum-genesis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ include "goquorum-genesis.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "goquorum-genesis.chart" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook-delete-policy: "hook-succeeded"
spec:
  backoffLimit: 3
  completions: 1
  template:
    metadata:
      labels:
        aadpodidbinding: "{{ .Values.azure.identityName }}"
        app.kubernetes.io/name: {{ include "goquorum-genesis.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "goquorum-genesis.name" . }}-sa
      restartPolicy: "Never"
      containers:
        - name: generate-genesis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            runAsUser: 0
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
          args:
            - |

              function safeWriteSecret {
                key=$1
                fpath=$2
                az keyvault secret show --vault-name {{ .Values.azure.keyvaultName }} --name $key > /dev/null 2>&1
                if [ $? -ne 0 ]; then
                  az keyvault secret set --vault-name {{ .Values.azure.keyvaultName }} --name $key --file $fpath --encoding utf-8
                else
                  # if the key exists pull it from keyvault so that when you update the enodes configmap, you have the right value
                  az keyvault secret show --vault-name {{ .Values.azure.keyvaultName }} --name $key | jq -r '.value' > $fpath
                fi
              }

              function safeWriteGenesisConfigmap {
                kubectl get configmap --namespace {{ .Release.Namespace }} goquorum-genesis
                if [ $? -ne 0 ]; then
                  kubectl create configmap --namespace {{ .Release.Namespace }} goquorum-genesis --from-file=genesis.json=/generated-config/genesis.json
                fi
              }

              function safeWriteEnodesConfigmap {
                kubectl get configmap --namespace {{ .Release.Namespace }} goquorum-node-enodes
                if [ $? -ne 0 ]; then
                  kubectl create configmap --namespace {{ .Release.Namespace }} goquorum-node-enodes --from-file=static-nodes.json=/generated-config/static-nodes.json
                fi
              }

              az login --identity --debug

              mkdir /generated-config/ && cd /generated-config/
              echo "Creating config ..."
              /opt/istanbul-tools/bin/istanbul setup --num {{ .Values.rawGenesisConfig.blockchain.nodes.count }} --nodes --quorum --save --verbose

              echo "Creating genesis configmap ..."
              safeWriteGenesisConfigmap

              # create the static-nodes with proper dns names for the quorum nodes
              echo "[" > /generated-config/static-nodes.json

              # 0 index so setting this to the num of validators
              for f in `seq 0 $(( {{ .Values.rawGenesisConfig.blockchain.nodes.count  }} -1 ))`; do mv $f "validator-$(($f + 1))" ; done

              echo "Creating validator keys ..."
              for v in `seq 1 {{ .Values.rawGenesisConfig.blockchain.nodes.count  }}`; do
                validatorKey="validator-$v"
                /opt/istanbul-tools/bin/bootnode -nodekey /generated-config/$validatorKey/nodekey -writeaddress > /generated-config/$validatorKey/nodekey.pub
                echo -ne $(cat /generated-config/$validatorKey/nodekey.pub) > /generated-config/$validatorKey/enode

                echo "Creating keys in keyvault for $validatorKey ..."
                safeWriteSecret goquorum-node-$validatorKey-nodekey /generated-config/$validatorKey/nodekey
                safeWriteSecret goquorum-node-$validatorKey-nodekeypub /generated-config/$validatorKey/nodekey.pub
                safeWriteSecret goquorum-node-$validatorKey-enode /generated-config/$validatorKey/enode

                # add to the static-nodes
                pubkey=$(cat /generated-config/$validatorKey/nodekey.pub )
                echo ",\"enode://$pubkey@goquorum-node-$validatorKey-0.goquorum-node-$validatorKey.{{ .Release.Namespace }}.svc.cluster.local:30303?discport=0\"" >> /generated-config/static-nodes.json
              done

              echo "]" >> /generated-config/static-nodes.json
              # remove the extra comma to make it valid json
              sed -i '0,/,/s///' /generated-config/static-nodes.json
              echo "Creating enodes configmap ..."
              safeWriteEnodesConfigmap

              echo "Completed"
