{{- if .Values.ingress_http.enabled -}}
{{- $fullName := include "besu-node.fullname" . -}}
{{- $ingressPath := .Values.ingress_http.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-http
  labels:
    app: {{ include "besu-node.name" . }}
    chart: {{ include "besu-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress_http.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress_http.tls }}
  tls:
    {{- range .Values.ingress_http.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
{{- end }}
