
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: member3-sa
  namespace: quorum

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: member3-keys-read-role
  namespace: quorum
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [ "quorum-member3-nodekey", "quorum-member3-accountkey" ]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: member3-rb
  namespace: quorum
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: member3-keys-read-role
subjects:
- kind: ServiceAccount
  name: member3-sa
  namespace: quorum

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: member3
  labels:
    app: member3
  namespace: quorum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member3
  serviceName: quorum-member3
  template:
    metadata:
      labels:
        app: member3
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9545"
        prometheus.io/path: "/debug/metrics/prometheus"   
    spec:
      serviceAccountName: member3-sa
      initContainers:
        - name: init-bootnode
          image: curlimages/curl:7.79.1
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec 
              curl -X GET --connect-timeout 30 --max-time 10 --retry 6 --retry-delay 0 --retry-max-time 300 http://quorum-rpcnode.quorum.svc.cluster.local:8545
              sleep 30
      containers:
        - name: member3-tessera
          image: quorumengineering/tessera:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TESSERA_CONFIG_TYPE
              value: "-09"              
          volumeMounts:
            - name: keys
              mountPath: /config/keys/
              readOnly: true   
            - name: data
              mountPath: /data
          ports:
            - containerPort: 9000
              name: tessera
              protocol: TCP
            - containerPort: 9080
              name: tessera-tp
              protocol: TCP
            - containerPort: 9101
              name: tessera-q2t
              protocol: TCP                 
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec 
              mkdir /data/tm/;
              cp /config/keys/tm.* /data/tm/ ;

                  cat <<EOF > /data/tm/tessera-config-09.json
                  {
                    "useWhiteList": false,
                    "jdbc": {
                      "username": "sa",
                      "password": "",
                      "url": "jdbc:h2:./data/tm/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
                      "autoCreateTables": true
                    },
                    "serverConfigs":[
                    {
                      "app":"ThirdParty",
                      "enabled": true,
                      "serverAddress": "http://quorum-member3.quorum.svc.cluster.local:9080",
                      "communicationType" : "REST"
                    },
                    {
                      "app":"Q2T",
                      "enabled": true,
                      "serverAddress": "http://quorum-member3.quorum.svc.cluster.local:9101",
                      "sslConfig": {
                        "tls": "OFF"
                      },
                      "communicationType" : "REST"     
                    },
                    {
                      "app":"P2P",
                      "enabled": true,
                      "serverAddress": "http://quorum-member3.quorum.svc.cluster.local:9000",
                      "sslConfig": {
                        "tls": "OFF"
                      },
                      "communicationType" : "REST"
                    }
                    ],
                    "peer": [
                      {
                          "url": "http://quorum-member1.quorum.svc.cluster.local:9000"
                      },
                      {
                          "url": "http://quorum-member2.quorum.svc.cluster.local:9000"
                      },
                      {
                          "url": "http://quorum-member3.quorum.svc.cluster.local:9000"
                      }
                    ],
                    "keys": {
                      "passwords": [],
                      "keyData": [
                        {
                          "config": $$(cat /data/tm/tm.key),
                          "publicKey": "$$(cat /data/tm/tm.pub)"
                        }
                      ]
                    },
                    "alwaysSendTo": []
                  }
              EOF

                  cat /data/tm/tessera-config-09.json
                  /tessera/bin/tessera -configfile /data/tm/tessera-config-09.json

        - name: member3-quorum
          image: quorumengineering/quorum:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUORUM_NETWORK_ID
              value: "10"              
            - name: QUORUM_CONSENSUS
              value: istanbul                
            - name: QUORUM_PTM_URL
              value: http://localhost:9101
          volumeMounts:
            - name: keys
              mountPath: /config/keys/
              readOnly: true   
            - name: static-nodes-file
              mountPath: /config/static-nodes
              readOnly: true
            - name: permissions-nodes-config
              mountPath: /config/permissions-nodes/
              readOnly: true
            - name: genesis-file
              mountPath: /config/quorum/
              readOnly: true
            - name: data
              mountPath: /data
          ports:
            - containerPort: 8545
              name: json-rpc
              protocol: TCP
            - containerPort: 8546
              name: ws
              protocol: TCP
            - containerPort: 8547
              name: graphql
              protocol: TCP
            - containerPort: 30303
              name: rlpx
              protocol: TCP
            - containerPort: 30303
              name: discovery
              protocol: UDP
            - containerPort: 9545
              name: metrics
              protocol: TCP                
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec
              apk add curl
              
              until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:9000/upcheck); do echo 'waiting for transaction manager to start...'; sleep 5; done;
              echo transaction manager is up;
 
              mkdir -p /data/dd
              cp /config/static-nodes/static-nodes.json /data/dd/
              cp /config/permissions-nodes/*.json /data/dd/
              cp /config/quorum/genesis.json /data/dd/
              geth --datadir=/data/dd init /config/quorum/genesis.json
              cp /config/keys/accountkey /data/dd/keystore/key
              cp /config/keys/nodekey /data/dd/geth/nodekey

              geth \
              --datadir /data/dd \
              --nodiscover \
              --nat=any \
              --permissioned \
              --emitcheckpoints \
              --verbosity 5 \
              --istanbul.blockperiod 5 --mine --minerthreads 1 --emitcheckpoints \
              --syncmode full --nousb \
              --networkid ${QUORUM_NETWORK_ID} \
              --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul \
              --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul \
              --ptm.timeout 5 --ptm.url $${QUORUM_PTM_URL} --ptm.http.writebuffersize 4096 --ptm.http.readbuffersize 4096 --ptm.tls.mode off \
              --port 30303 \
              --unlock 0 \
              --allow-insecure-unlock \
              --metrics --pprof --pprofaddr 0.0.0.0 --pprofport 9545 \
              --password /config/keys/password.txt

      volumes:
        - name: keys
          secret:
            secretName: quorum-member3-keys
        - name: genesis-file
          configMap:
            name: goquorum-genesis-configmap
            items:
              - key: genesis.json
                path: genesis.json                 
        - name: static-nodes-file
          configMap:
            name: quorum-static-nodes-configmap
            items:
              - key: static-nodes.json
                path: static-nodes.json 
        - name: permissions-nodes-config
          configMap:
            name: quorum-permissions-nodes-configmap
        - name: data
          emptyDir:
            sizeLimit: "2Gi"

 
