
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: validator3-sa
  namespace: quorum

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: validator3-keys-read-role
  namespace: quorum
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: [ "quorum-validator3-keys" ]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: validator3-rb
  namespace: quorum
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: validator3-keys-read-role
subjects:
- kind: ServiceAccount
  name: validator3-sa
  namespace: quorum

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: validator3
  labels:
    app: validator3
  namespace: quorum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator3
  serviceName: quorum-validator3
  template:
    metadata:
      labels:
        app: validator3
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9545"
        prometheus.io/path: "/debug/metrics/prometheus"   
    spec:
      serviceAccountName: validator3-sa
      initContainers:
        - name: init-bootnode
          image: curlimages/curl:7.79.1
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec 
              curl -X GET --connect-timeout 30 --max-time 10 --retry 6 --retry-delay 0 --retry-max-time 300 http://quorum-validator1.quorum.svc.cluster.local:8545
              sleep 30
              curl -X GET --connect-timeout 30 --max-time 10 --retry 6 --retry-delay 0 --retry-max-time 300 http://quorum-validator2.quorum.svc.cluster.local:8545
              sleep 30
      containers:
        - name: validator3
          image: quorumengineering/quorum:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUORUM_NETWORK_ID
              value: "10"              
            - name: QUORUM_CONSENSUS
              value: istanbul               
            - name: PRIVATE_CONFIG
              value: ignore        
          volumeMounts:
            - name: keys
              mountPath: /config/keys/
              readOnly: true
            - name: static-nodes-file
              mountPath: /config/static-nodes
              readOnly: true
            - name: permissions-nodes-config
              mountPath: /config/permissions-nodes/
              readOnly: true
            - name: genesis-file
              mountPath: /config/quorum/
              readOnly: true
            - name: data
              mountPath: /data
          ports:
            - containerPort: 8545
              name: json-rpc
              protocol: TCP
            - containerPort: 8546
              name: ws
              protocol: TCP
            - containerPort: 8547
              name: graphql
              protocol: TCP
            - containerPort: 30303
              name: rlpx
              protocol: TCP
            - containerPort: 30303
              name: discovery
              protocol: UDP
            - containerPort: 9545
              name: metrics
              protocol: TCP                
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec 
              cp /config/static-nodes/static-nodes.json /data/
              cp /config/permissions-nodes/*.json /data/
              cp /config/quorum/genesis.json /data/
              geth --datadir=/data init /config/quorum/genesis.json
              cp /config/keys/accountkey /data/keystore/key
              cp /config/keys/nodekey /data/geth/nodekey

              geth \
              --datadir /data \
              --nodiscover \
              --nat=any \
              --permissioned \
              --emitcheckpoints \
              --verbosity 5 \
              --istanbul.blockperiod 5 --mine --miner.threads 1 --emitcheckpoints \
              --syncmode full --nousb \
              --networkid ${QUORUM_NETWORK_ID} \
              --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul \
              --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul \
              --port 30303 \
              --unlock 0 \
              --allow-insecure-unlock \
              --metrics --pprof --pprof.addr 0.0.0.0 --pprof.port 9545 \
              --password /config/keys/password.txt 
          livenessProbe:
            httpGet:
              path: /
              port: 8545
            initialDelaySeconds: 120
            periodSeconds: 30  

      volumes:
        - name: keys
          secret:
            secretName: quorum-validator3-keys
        - name: accountkey
          secret:
            secretName: quorum-validator3-accountkey
        - name: genesis-file
          configMap:
            name: goquorum-genesis-configmap
            items:
              - key: genesis.json
                path: genesis.json                
        - name: static-nodes-file
          configMap:
            name: quorum-static-nodes-configmap
            items:
              - key: static-nodes.json
                path: static-nodes.json 
        - name: permissions-nodes-config
          configMap:
            name: quorum-permissions-nodes-configmap
        - name: data
          emptyDir:
            sizeLimit: "2Gi"

 
