---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorum-explorer.fullname" . }}-config
  labels:
    app.kubernetes.io/name: quorum-explorer-cleanup
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: {{ include "quorum-explorer.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/managed-by: helm
  namespace: {{ .Release.Namespace }}
data:
  config.json: {{ .Values.explorerConfig | toJson }}
  .env.production: {{ .Values.explorerEnvConfig | toJson }}