apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quorum-explorer.fullname" . }}
  labels:
    app.kubernetes.io/name: quorum-explorer-deployment
    app.kubernetes.io/component: deployment
    app.kubernetes.io/part-of: {{ include "quorum-explorer.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/managed-by: helm
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quorum-explorer-deployment
      app.kubernetes.io/component: deployment
      app.kubernetes.io/part-of: {{ include "quorum-explorer.fullname" . }}
      app.kubernetes.io/namespace: {{ .Release.Namespace }}
      app.kubernetes.io/managed-by: helm
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quorum-explorer-deployment
        app.kubernetes.io/component: deployment
        app.kubernetes.io/part-of: {{ include "quorum-explorer.fullname" . }}
        app.kubernetes.io/namespace: {{ .Release.Namespace }}
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - image: {{ .Values.image.explorer.repository }}:{{ .Values.image.explorer.tag }}
          imagePullPolicy: {{ .Values.image.explorer.pullPolicy }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 30
          name: {{ .Release.Name }}
          env:
            - name: "REACT_APP_ENVIRONMENT"
              value: "PROD"
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: config-volume
            mountPath: /app/config.json
            subPath: config.json
          - name: config-volume
            mountPath: /app/.env.production
            subPath: .env.production
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "quorum-explorer.fullname" . }}-config
      dnsPolicy: ClusterFirst
