apiVersion: v1
kind: Service
metadata:
  name: {{ include "quorum-explorer.fullname" . }}
  labels:
    app: {{ template "quorum-explorer.fullname" . }}
    chart: {{ template "quorum-explorer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ include "quorum-explorer.fullname" . }}
    helm.sh/chart: {{ include "quorum-explorer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 25000
  selector:
    app: {{ .Release.Name }}
  sessionAffinity: None
  type: NodePort
