apiVersion: v1
kind: Service
metadata:
  name: {{ include "quorum-explorer.fullname" . }}
  labels:
    app.kubernetes.io/name: quorum-explorer-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ include "quorum-explorer.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/managed-by: helm
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 25000
  selector:
    app.kubernetes.io/part-of: {{ include "quorum-explorer.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
  sessionAffinity: None
  type: NodePort
