{
 "title": "goQuorum Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "validator*" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(chain_head_block{}, instance)"
    }
   },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance) (chain_head_block)"
    },
    {
     "expr": "sum by (instance) (1/rate(chain_head_block[5m]))"
    },
    { "expr": "(p2p_peers)" }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Latest Block",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "chain_head_block", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Block Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "abs(1/rate(chain_head_block[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "chain_validation{quantile=\"$quantile\"} ",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "chain_write{quantile=\"$quantile\"}",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "chain_account_reads{quantile=\"$quantile\"}",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "chain_account_updates{quantile=\"$quantile\"}",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "chain_account_hashes{quantile=\"$quantile\"}",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "chain_account_commits{quantile=\"$quantile\"}",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "chain_storage_reads{quantile=\"$quantile\"}",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "chain_storage_updates{quantile=\"$quantile\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "chain_storage_hashes{quantile=\"$quantile\"}",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "chain_storage_commits{quantile=\"$quantile\"}",
     "legendFormat": "storage commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "txpool_pending", "legendFormat": "executable" },
    { "expr": "txpool_queued", "legendFormat": "gapped" },
    {
     "expr": "txpool_local{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(txpool_valid[1m])", "legendFormat": "valid" },
    { "expr": "rate(txpool_invalid[1m])", "legendFormat": "invalid" },
    { "expr": "rate(txpool_underpriced[1m])", "legendFormat": "underpriced" },
    {
     "expr": "rate(txpool_pending_discard[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  { "title": "DevP2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(p2p_peers)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rate(p2p_ingress[1m])", "legendFormat": "ingress {{instance}}" },
    { "expr": "rate(p2p_egress[1m])", "legendFormat": "egress {{instance}}" }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "legendFormat": "leveldb read {{instance}}"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write[1m])",
     "legendFormat": "leveldb write {{instance}}"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read[1m])",
     "legendFormat": "ancient read {{instance}}"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write[1m])",
     "legendFormat": "ancient write {{instance}}"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_read{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "leveldb read"
    },
    { "expr": "eth_db_chaindata_disk_write", "legendFormat": "leveldb write" },
    { "expr": "eth_db_chaindata_ancient_read", "legendFormat": "ancient read" },
    { "expr": "eth_db_chaindata_ancient_write", "legendFormat": "ancient write" }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "eth_db_chaindata_disk_size", "legendFormat": "leveldb [{{instance}}]" },
    { "expr": "eth_db_chaindata_ancient_size", "legendFormat": "ancient [{{instance}}]" }
   ]
  },
  { "title": "Trie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Clean cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_read[1m])",
     "legendFormat": "hit [{{instance}}]"
    },
    {
     "expr": "rate(trie_memcache_clean_write[1m])",
     "legendFormat": "miss [{{instance}}]"
    }
   ]
  },
  {
   "title": "Dirty cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_size[1m])",
     "legendFormat": "gc {{instance}}"
    },
    {
     "expr": "rate(trie_memcache_flush_size[1m])",
     "legendFormat": "overflow {{instance}}"
    },
    {
     "expr": "rate(trie_memcache_commit_size[1m])",
     "legendFormat": "commit {{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "system_cpu_sysload", "legendFormat": "system [{{instance}}]" },
    { "expr": "system_cpu_syswait", "legendFormat": "iowait [{{instance}}]" },
    { "expr": "system_cpu_procload", "legendFormat": "geth [{{instance}}]" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rate(system_memory_allocs[1m])", "legendFormat": "alloc [{{instance}}]" },
    { "expr": "system_memory_used", "legendFormat": "used [{{instance}}]" },
    { "expr": "system_memory_held", "legendFormat": "held [{{instance}}]" }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes[1m])",
     "legendFormat": "read [{{instance}}]"
    },
    {
     "expr": "rate(system_disk_writebytes[1m])",
     "legendFormat": "write [{{instance}}]"
    }
   ]
  }
 ]
}