
{{- if eq .Values.provider "aws" }}

---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "goquorum-node.fullname" . }}-azure-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects:  |
      - objectName: {{ include "goquorum-node.fullname" . }}-nodekey
        objectType: secretsmanager
        objectAlias: nodekey
        objectVersion: ""
      - objectName: {{ include "goquorum-node.fullname" . }}-nodekeypub
        objectAlias: nodekey.pub
        objectType: secretsmanager
        objectVersion: ""
      - objectName: {{ include "goquorum-node.fullname" . }}-enode
        objectAlias: enode
        objectType: secretsmanager
        objectVersion: ""
      {{- if .Values.nodeFlags.privacy }}
      - objectName: {{ include "goquorum-node.fullname" . }}-tmkey
        objectAlias: tm.key
        objectType: secretsmanager
        objectVersion: ""
      - objectName: {{ include "goquorum-node.fullname" . }}-tmkeypub
        objectAlias: tm.pub
        objectType: secretsmanager
        objectVersion: ""
      - objectName: {{ include "goquorum-node.fullname" . }}-tmpassword
        objectAlias: tm.password
        objectType: secretsmanager
        objectVersion: ""
      {{- end }}

{{- end }}