{{- if eq .Values.provider "azure" }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goquorum-node.fullname" . }}-hooks-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install,pre-delete,post-delete"

{{- end}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "goquorum-node.fullname" . }}-hooks-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install,pre-delete,post-delete"
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create", "get", "list", "update", "delete" ]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "goquorum-node.fullname" . }}-hooks-rb
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install,pre-delete,post-delete"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "goquorum-node.fullname" . }}-hooks-role
subjects:
- kind: ServiceAccount
  namespace:  {{ .Release.Namespace }}
{{- if eq .Values.provider "azure" }}
  name: {{ include "goquorum-node.fullname" . }}-hooks-sa
{{- else }}
  name: {{ .Values.aws.serviceAccountName }}
{{- end}}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "goquorum-node.fullname" . }}-pre-install-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded"
{{- if eq .Values.provider "azure" }}
  labels:
    aadpodidbinding: "{{ .Values.azure.identityName }}"
{{- end}}
spec:
  backoffLimit: 1
  completions: 1
  template:
{{- if eq .Values.provider "azure" }}
    metadata:
      labels:
        aadpodidbinding: "{{ .Values.azure.identityName }}"
{{- end}}
    spec:
{{- if eq .Values.provider "azure" }}
      serviceAccountName: {{ include "goquorum-node.fullname" . }}-hooks-sa
{{- else }}
      serviceAccountName: {{ .Values.aws.serviceAccountName }}
{{- end}}

      restartPolicy: "OnFailure"
      containers:
      - name: {{ template "goquorum-node.fullname" . }}-quorum-pre-start-hook
        image: "{{ .Values.image.hooks.repository }}:{{ .Values.image.hooks.tag }}"
        imagePullPolicy: {{ .Values.image.hooks.pullPolicy }}
        securityContext:
          runAsUser: 0
        command:
          - /bin/bash
          - -c
        args:
          - |

            echo "{{ template "goquorum-node.fullname" . }} Pre Install hook ..."

{{- if eq .Values.provider "azure" }}

            function safeWriteSecret {
              key=$1
              fpath=$2
              az keyvault secret show --vault-name {{ .Values.azure.keyvaultName }} --name $key > /dev/null 2>&1
              if [ $? -ne 0 ]; then
                az keyvault secret set --vault-name {{ .Values.azure.keyvaultName }} --name $key --file $fpath --encoding utf-8
              else
                # if the key exists pull it from keyvault so that when you update the enodes configmap, you have the right value
                az keyvault secret show --vault-name {{ .Values.azure.keyvaultName }} --name $key | jq -r '.value' > $fpath
              fi
            }
            az login --identity --debug

{{- else }}

            function safeWriteSecret {
              key=$1
              fpath=$2
              aws secretsmanager describe-secret --secret-id $key > /dev/null 2>&1
              if [ $? -ne 0 ]; then
                aws secretsmanager create-secret --name $key --description $key --secret-string file://$fpath
              else
                # if the key exists pull it from keyvault so that when you update the enodes configmap, you have the right value
                aws secretsmanager get-secret-value --secret-id $key | jq -r '.SecretString' > $fpath
              fi
            }
{{- end }}

            function update_enodes_configmap {
              kubectl -n {{ .Release.Namespace }} get configmap goquorum-node-enodes -o json
              if [ $? -ne 0 ]; then
                  echo "[]" > /tmp/static-nodes.json.raw
              fi
              # update the entries
              echo "updating goquorum-node-enodes..."
              pubkey=$(cat /tmp/nodekey.pub )
              echo $(kubectl -n {{ .Release.Namespace }} get configmap goquorum-node-enodes -o jsonpath='{.data.static-nodes\.json}' ) > /tmp/static-nodes.json.raw
              NEEDLE="enode://$pubkey@{{ template "goquorum-node.fullname" . }}-0.{{ template "goquorum-node.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:30303?discport=0"
              cat /tmp/static-nodes.json.raw | jq --arg NEEDLE "$NEEDLE" '. += [ $NEEDLE ] | unique ' > /tmp/static-nodes.json
              kubectl -n {{ .Release.Namespace }} create configmap goquorum-node-enodes --from-file=static-nodes.json=/tmp/static-nodes.json -o yaml --dry-run | kubectl replace -f -
            }

            function update_tessera_peers_configmap {
              kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o json
              # first time a tx node is deployed and there is no configmap
              if [ $? -ne 0 ]; then
                echo "No tessera-peers found, creating a new one..."
                echo "[{ \"url\": \"http://{{ template "goquorum-node.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:9000\" }]"  > /tmp/tessera-peers
                kubectl --namespace {{ .Release.Namespace }} create configmap tessera-peers --from-file=tesseraPeers=/tmp/tessera-peers

              # update the entries
              else
                echo "Tessera-peers found, updating existing..."
                echo $(kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o jsonpath='{.data.tesseraPeers}' ) > /tmp/tessera-peers.raw
                NEEDLE="http://{{ template "goquorum-node.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:9000"
                cat /tmp/tessera-peers.raw | jq --arg NEEDLE "$NEEDLE" '. += [{"url": $NEEDLE}] | unique ' > /tmp/tessera-peers
                kubectl -n {{ .Release.Namespace }} create configmap tessera-peers --from-file=tesseraPeers=/tmp/tessera-peers -o yaml --dry-run | kubectl replace -f -
              fi
            }

            echo "Quorum nodekey generation ..."
            cd /tmp
            /opt/istanbul-tools/bin/bootnode -genkey /tmp/nodekey --writeaddress > /tmp/nodekey.pub
            echo -ne $(cat /tmp/nodekey.pub) > /tmp/enode


            echo "Creating keys in vault for {{ template "goquorum-node.fullname" . }} ..."
            safeWriteSecret {{ template "goquorum-node.fullname" . }}-nodekey /tmp/nodekey
            safeWriteSecret {{ template "goquorum-node.fullname" . }}-nodekeypub /tmp/nodekey.pub
            safeWriteSecret {{ template "goquorum-node.fullname" . }}-enode /tmp/enode
            update_enodes_configmap

          {{- if .Values.nodeFlags.privacy }}

          {{- if .Values.node.tessera.password }}
            echo $'{{ .Values.node.tessera.password  }}\n{{ .Values.node.tessera.password }}\n' > /tmp/password.txt
          {{- else }}
            echo $'\n\n' > /tmp/password.txt
          {{- end }}

            /opt/tessera/bin/tessera -keygen -filename /tmp/tm < /tmp/password.txt

            echo "Creating tessera keys in keyvault for {{ template "goquorum-node.fullname" . }} ..."
            safeWriteSecret {{ template "goquorum-node.fullname" . }}-tmkey /tmp/tm.key
            safeWriteSecret {{ template "goquorum-node.fullname" . }}-tmkeypub /tmp/tm.pub
            echo -ne $(sed -n '1p' /tmp/password.txt )> /tmp/password
            safeWriteSecret {{ template "goquorum-node.fullname" . }}-tmpassword /tmp/password

            update_tessera_peers_configmap

          {{- end }}
            echo "Completed"


---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "goquorum-node.fullname" . }}-pre-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "hook-succeeded"
{{- if eq .Values.provider "azure" }}
  labels:
    aadpodidbinding: "{{ .Values.azure.identityName }}"
{{- end}}
spec:
  backoffLimit: 3
  completions: 1
  template:
{{- if eq .Values.provider "azure" }}
    metadata:
      labels:
        aadpodidbinding: "{{ .Values.azure.identityName }}"
{{- end}}
    spec:
{{- if eq .Values.provider "azure" }}
      serviceAccountName: {{ include "goquorum-node.fullname" . }}-hooks-sa
{{- else }}
      serviceAccountName: {{ .Values.aws.serviceAccountName }}
{{- end}}
      restartPolicy: "OnFailure"
      containers:
        - name: {{ template "goquorum-node.fullname" . }}-node-pre-delete-hook
          image: "{{ .Values.image.hooks.repository }}:{{ .Values.image.hooks.tag }}"
          imagePullPolicy: {{ .Values.image.hooks.pullPolicy }}
          command:
            - /bin/bash
            - -c
          args:
            - |

              echo "{{ template "goquorum-node.fullname" . }} Pre Delete hook ..."

              function delete_node_from_tessera_peers_configmap {
               kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o json
               # if there is no configmap, do nothing
               if [ $? -ne 0 ]; then
                 echo "No tessera-peers found, nothing to do..."
               # delete the one
               else
                 echo "tessera-peers found, deleting {{ template "goquorum-node.fullname" . }}..."
                 echo $(kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o jsonpath='{.data.tesseraPeers}' ) > /tmp/tessera-peers.raw
                 cat /tmp/tessera-peers.raw | jq --arg NEEDLE "{{ template "goquorum-node.fullname" . }}" 'del(.[] | select( .url | contains($NEEDLE) ))' > /tmp/tessera-peers
                 kubectl -n {{ .Release.Namespace }} create configmap tessera-peers --from-file=tesseraPeers=/tmp/tessera-peers -o yaml --dry-run | kubectl replace -f -
               fi
              }

              function delete_node_from_enodes_configmap {
               kubectl -n {{ .Release.Namespace }}  get configmap goquorum-node-enodes -o json
               # if there is no configmap, do nothing
               if [ $? -ne 0 ]; then
                 echo "No peers found, nothing to do..."
               # delete the one
               else
                 echo "goquorum-node-enodes found, deleting {{ template "goquorum-node.fullname" . }}..."
                 echo $(kubectl -n {{ .Release.Namespace }} get configmap goquorum-node-enodes -o jsonpath='{.data.static-nodes\.json}' ) > /tmp/static-nodes.json.raw
                 cat /tmp/static-nodes.json.raw | jq --arg NEEDLE "{{ template "goquorum-node.fullname" . }}" 'del(.[] | select( . | contains($NEEDLE) ))' > /tmp/static-nodes.json
                 kubectl -n {{ .Release.Namespace }} create configmap goquorum-node-enodes --from-file=static-nodes.json=/tmp/static-nodes.json -o yaml --dry-run | kubectl replace -f -
               fi
              }

              delete_node_from_tessera_peers_configmap
              delete_node_from_enodes_configmap

              echo "Completed"
