apiVersion: v1
version: 0.1.1
name: quorum-explorer
description: Quorum Explorer
keywords:
  - ethereum
  - besu
  - hyperledger
  - enterprise
  - blockchain
  - pegasys
  - consensys
  - explorer
sources:
  - https://github.com/ConsenSys/quorum-explorer
maintainers:
  - name: Joshua Fernandes
    email: joshua.fernandes@consensys.net
  - name: Eric Lin
    email: eric.lin@consensys.net
icon: http://besu.hyperledger.org/en/latest/favicon.ico