apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "besu-monitoring.fullname" . }}-prometheus-configmap
  labels:
    app: {{ template "besu-monitoring.fullname" . }}-prometheus-configmap
    chart: {{ template "besu-monitoring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |-
{{ .Files.Get "prometheus.yml" | indent 4}}