apiVersion: v1
kind: Service
metadata:
  name: {{ template "besu-monitoring.fullname" . }}-grafana
  labels:
    app: {{ template "besu-monitoring.name" . }}
    chart: {{ template "besu-monitoring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    component: grafana
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    component: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030
      protocol: TCP
      name: grafana

