apiVersion: v1
kind: Service
metadata:
  name: besu-validator4
  labels:
    app: validator4
  namespace: besu
spec:
  type: ClusterIP
  selector:
    app: validator4
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: discovery
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: rlpx
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: json-rpc
    - port: 8546
      targetPort: 8546
      protocol: TCP
      name: ws
    - port: 8547
      targetPort: 8547
      protocol: TCP
      name: graphql
