{{- $orionNumber := "orion1" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "besu.fullname" . }}-{{ $orionNumber }}
  labels:
    app: {{ template "besu.name" . }}
    chart: {{ template "besu.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
    component: {{ $orionNumber }}
spec:
  replicas: {{ .Values.node.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "besu.name" . }}
      release: {{ .Release.Name }}
      component: {{ $orionNumber }}
  serviceName: "{{ $orionNumber }}-service"
  template:
    metadata:
      labels:
        app: {{ template "besu.name" . }}
        release: {{ .Release.Name }}
        component: {{ $orionNumber }}
    spec:
      containers:
        - name: {{ $orionNumber }}
          image: {{ .Values.image.orion.repository }}:{{ .Values.image.orion.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: key
              mountPath: /secrets
              readOnly: true
            - name: key-password
              mountPath: /passwords
              readOnly: true
            - name: orion-conf
              mountPath: /configs-ro
              readOnly: true
            - name: orion-pubkey
              mountPath: /configs/keys
              readOnly: true
            - name: data
              mountPath: /data
            - name: orion-init
              mountPath: /scripts/orion-init.sh
              subPath: orion-init.sh
          ports:
            - containerPort: 8888
              name: nodeport
              protocol: TCP
            - containerPort: 8080
              name: clientport
              protocol: TCP
          command:
            - /bin/sh
            - -c
            - /scripts/orion-init.sh
          livenessProbe:
            httpGet:
              path: /upcheck
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /upcheck
              port: 8888
            initialDelaySeconds: 180
            periodSeconds: 30
      volumes:
        - name: orion-conf
          configMap:
            name: besu-configmap-{{ $orionNumber }}-conf
            items:
              - key: {{ $orionNumber }}.conf
                path: orion.conf
        - name: orion-pubkey
          configMap:
            name: besu-configmap-{{ $orionNumber }}-conf
            items:
              - key: {{ $orionNumber }}PubKey
                path: orion.pub
        - name: key
          secret:
            secretName: besu-{{ $orionNumber }}-key-secret
            items:
              - key: {{ $orionNumber }}.key
                path: key
        - name: key-password
          secret:
            secretName: besu-{{ $orionNumber }}-key-secret
            items:
              - key: {{ $orionNumber }}.password
                path: orion.password
        - name: orion-init
          configMap:
            name: besu-orion-init
            defaultMode: 0777
        - name: data
          emptyDir:
            sizeLimit: "{{ .Values.orions.pvcSizeLimit }}"