---
image:
  repository: consensys/quorum-k8s-hooks
  tag: latest
  pullPolicy: Always

# local / azure
provider: local

# the number of Validators you want
rawGenesisConfig:
  blockchain:
    nodes:
      count: 4