apiVersion: v1
kind: Service
metadata:
  name: {{ template "quorum.fullname" . }}-grafana
  labels:
    app: {{ template "quorum.name" . }}
    chart: {{ template "quorum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: monitoring
    component: grafana
  namespace: monitoring
spec:
  type: NodePort
  selector:
    component: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030
      protocol: TCP
      name: grafana
