---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "quorum.name" . }}-member1-keys
  labels:
    app: {{ template "quorum.name" . }}
    chart: {{ template "quorum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.nodes.member1.nodekey }}
  nodekey: |-
    {{ .Values.nodes.member1.nodekey  | b64enc }}
  {{- end }}
  {{- if .Values.nodes.member1.accountkey }}
  accountkey: |-
    {{ .Values.nodes.member1.accountkey | b64enc }}
  {{- end }}
  {{- if .Values.nodes.member1.password }}
  password.txt: |-
    {{ .Values.nodes.member1.password  | b64enc }}
  {{- end }}
  {{- if .Values.nodes.member1.tmkey }}
  tm.key: |-
    {{ .Values.nodes.member1.tmkey  | b64enc }}
  {{- end }}
  {{- if .Values.nodes.member1.tmpub }}
  tm.pub: |-
    {{ .Values.nodes.member1.tmpub  | b64enc }}
  {{- end }}  