---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "quorum.name" . }}-member2-keys
  labels:
    app: {{ template "quorum.name" . }}
    chart: {{ template "quorum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.nodes.member2.nodekey }}
  nodekey: |-
    {{ .Values.nodes.member2.nodekey  | b64enc }}
  {{- end }}
  {{- if .Values.nodes.member2.accountkey }}
  accountkey: |-
    {{ .Values.nodes.member2.accountkey | b64enc }}
  {{- end }}
  {{- if .Values.nodes.member2.password }}
  password.txt: |-
    {{ .Values.nodes.member2.password  | b64enc }}
  {{- end }}
  {{- if .Values.nodes.member2.tmkey }}
  tm.key: |-
    {{ .Values.nodes.member2.tmkey  | b64enc }}
  {{- end }}
  {{- if .Values.nodes.member2.tmpub }}
  tm.pub: |-
    {{ .Values.nodes.member2.tmpub  | b64enc }}
  {{- end }}  
