---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "quorum.name" . }}-rpcnode-keys
  labels:
    app: {{ template "quorum.name" . }}
    chart: {{ template "quorum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.nodes.rpcnode.nodekey }}
  nodekey: |-
    {{ .Values.nodes.rpcnode.nodekey  | b64enc }}
  {{- end }}
  {{- if .Values.nodes.rpcnode.accountkey }}
  accountkey: |-
    {{ .Values.nodes.rpcnode.accountkey | b64enc }}
  {{- end }}
  {{- if .Values.nodes.rpcnode.password }}
  password.txt: |-
    {{ .Values.nodes.rpcnode.password  | b64enc }}
  {{- end }}
  {{- if .Values.nodes.rpcnode.tmkey }}
  tm.key: |-
    {{ .Values.nodes.rpcnode.tmkey  | b64enc }}
  {{- end }}
  {{- if .Values.nodes.rpcnode.tmpub }}
  tm.pub: |-
    {{ .Values.nodes.rpcnode.tmpub  | b64enc }}
  {{- end }}  