apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "quorum.name" . }}-static-nodes-configmap
  labels:
    app: {{ template "quorum.name" . }}
    chart: {{ template "quorum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
data:
  static-nodes.json: |-
{{ (tpl (.Files.Get "static-nodes.json") . | indent 4 ) }}



