---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "quorum.name" . }}-validator3-keys
  labels:
    app: {{ template "quorum.name" . }}
    chart: {{ template "quorum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.validators.validator3.nodekey }}
  nodekey: |-
    {{ .Values.validators.validator3.nodekey  | b64enc }}
  {{- end }}
  {{- if .Values.validators.validator3.accountkey }}
  accountkey: |-
    {{ .Values.validators.validator3.accountkey | b64enc }}
  {{- end }}
  {{- if .Values.validators.validator3.password }}
  password.txt: |-
    {{ .Values.validators.validator3.password  | b64enc }}
  {{- end }}
  {{- if .Values.validators.validator3.tmkey }}
  tm.key: |-
    {{ .Values.validators.validator3.tmkey  | b64enc }}
  {{- end }}
  {{- if .Values.validators.validator3.tmpub }}
  tm.pub: |-
    {{ .Values.validators.validator3.tmpub  | b64enc }}
  {{- end }}  
  