---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "quorum.name" . }}-validator1-keys
  labels:
    app: {{ template "quorum.name" . }}
    chart: {{ template "quorum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.validators.validator1.nodekey }}
  nodekey: |-
    {{ .Values.validators.validator1.nodekey  | b64enc }}
  {{- end }}
  {{- if .Values.validators.validator1.accountkey }}
  accountkey: |-
    {{ .Values.validators.validator1.accountkey | b64enc }}
  {{- end }}
  {{- if .Values.validators.validator1.password }}
  password.txt: |-
    {{ .Values.validators.validator1.password  | b64enc }}
  {{- end }}
