---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu-node.fullname" . }}
  labels:
    app: {{ template "besu-node.fullname" . }}
    chart: {{ template "besu-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ include "besu-node.fullname" . }}
    helm.sh/chart: {{ include "besu-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "besu-node.fullname" . }}
    release: {{ .Release.Name }}
    component: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: json-rpc
      port: {{ .Values.node.rpc.port }}
      targetPort: json-rpc
      protocol: TCP
    - name: ws
      port: {{ .Values.node.ws.port }}
      targetPort: ws
      protocol: TCP
    - name: graphql
      port: {{ .Values.node.graphql.port }}
      targetPort: graphql
      protocol: TCP
    - name: rlpx
      port: {{ .Values.node.p2p.port }}
      targetPort: rlpx
      protocol: TCP
    - name: discovery
      port: {{ .Values.node.p2p.port }}
      targetPort: discovery
      protocol: UDP
      
{{- if .Values.nodeFlags.privacy }}          
    - name: nodeport
      port: {{ .Values.privacy.orionConfig.nodeport }}
      targetPort: nodeport
      protocol: TCP
    - name: clientport
      port: {{ .Values.privacy.orionConfig.clientport }}
      targetPort: clientport
      protocol: TCP

{{- end }}    

