---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu-node.fullname" . }}
  labels:
    prometheus: besu-scrape
    app: {{ template "besu-node.fullname" . }}
    chart: {{ template "besu-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    helm.sh/chart: {{ include "besu-node.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "besu-node.fullname" . }}
    release: {{ .Release.Name }}
    component: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: json-rpc
      port: {{ .Values.node.besu.rpc.port }}
      targetPort: json-rpc
      protocol: TCP
    - name: ws
      port: {{ .Values.node.besu.ws.port }}
      targetPort: ws
      protocol: TCP
    - name: graphql
      port: {{ .Values.node.besu.graphql.port }}
      targetPort: graphql
      protocol: TCP
    - name: rlpx
      port: {{ .Values.node.besu.p2p.port }}
      targetPort: rlpx
      protocol: TCP
    - name: discovery
      port: {{ .Values.node.besu.p2p.port }}
      targetPort: discovery
      protocol: UDP
    - name: metrics
      port: {{ .Values.node.besu.metrics.port }}
      targetPort: metrics
      protocol: TCP
      
{{- if .Values.nodeFlags.privacy }}          
    - name: tessera
      port: {{ .Values.node.tessera.port }}
      targetPort: tessera
      protocol: TCP
    - name: tessera-tp
      port: {{ .Values.node.tessera.tpport }}
      targetPort: tessera-tp
      protocol: TCP
    - name: tessera-q2t
      port: {{ .Values.node.tessera.q2tport }}
      targetPort: tessera-q2t
      protocol: TCP
{{- end }}


{{- if and .Values.node.besu.metrics.enabled .Values.node.besu.metrics.serviceMonitor.enabled }}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "besu-node.fullname" . }}-servicemonitor
  labels:
    prometheus: besu-scrape
    name: {{ template "besu-node.fullname" . }}
    chart: {{ template "besu-node.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ include "besu-node.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      prometheus: besu-scrape
      app.kubernetes.io/name: {{ include "besu-node.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
    scheme: http
    honorLabels: true
{{- end }}

