---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "besu-node.fullname" . }}-hooks-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install,pre-delete,post-delete"  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "besu-node.fullname" . }}-hooks-role
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install,pre-delete,post-delete"    
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["create", "get", "list", "update", "delete" ]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "besu-node.fullname" . }}-hooks-rb
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install,pre-delete,post-delete"    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "besu-node.fullname" . }}-hooks-role
subjects:
- kind: ServiceAccount
  namespace:  {{ .Release.Namespace }}
{{- if and (eq .Values.provider "azure") (eq .Values.cloudSecretsStore true) }}
  name: {{ include "besu-node.fullname" . }}-hooks-sa
{{- else if and (eq .Values.provider "aws") (eq .Values.cloudSecretsStore true) }}
  name: {{ .Values.aws.serviceAccountName }}
{{- else }}
  name: {{ include "besu-node.fullname" . }}-hooks-sa
{{- end}}


---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "besu-node.fullname" . }}-pre-install-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "hook-succeeded"
  labels:
{{- if and (eq .Values.provider "azure") (eq .Values.cloudSecretsStore true) }}
    aadpodidbinding: "{{ .Values.azure.identityName }}"
{{- end }}
spec:
  backoffLimit: 1
  completions: 1
  template:
{{- if and (eq .Values.provider "azure") (eq .Values.cloudSecretsStore true) }}
    metadata:
      labels:
        aadpodidbinding: "{{ .Values.azure.identityName }}"
{{- end }}
    spec:
{{- if and (eq .Values.provider "azure") (eq .Values.cloudSecretsStore true) }}
      serviceAccountName: {{ include "besu-node.fullname" . }}-hooks-sa
{{- else if and (eq .Values.provider "aws") (eq .Values.cloudSecretsStore true) }}
      serviceAccountName: {{ .Values.aws.serviceAccountName }}
{{- else }}
      serviceAccountName: {{ include "besu-node.fullname" . }}-hooks-sa
{{- end }}
      restartPolicy: "OnFailure"
      containers:
        - name: {{ template "besu-node.fullname" . }}-pre-start-hook
          image: {{ .Values.image.hooks.repository }}:{{ .Values.image.hooks.tag }}
          imagePullPolicy: {{ .Values.image.besu.pullPolicy }}
          securityContext:
            runAsUser: 0
          command:
            - /bin/bash
            - -c
          args:
            - |

              function update_enodes_configmap {
                kubectl -n {{ .Release.Namespace }} get configmap besu-node-enodes -o json
                if [ $? -ne 0 ]; then
                echo "[]" > /tmp/static-nodes.json.raw
                fi
                # update the entries
                echo "updating besu-node-enodes..."
                pubkey=$(cat /tmp/enode )
                echo $(kubectl -n {{ .Release.Namespace }} get configmap besu-node-enodes -o jsonpath='{.data.static-nodes\.json}' ) > /tmp/static-nodes.json.raw
                NEEDLE="enode://$pubkey@{{ template "besu-node.fullname" . }}-0.{{ template "besu-node.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:30303?discport=0"
                cat /tmp/static-nodes.json.raw | jq --arg NEEDLE "$NEEDLE" '. += [ $NEEDLE ] | unique ' > /tmp/static-nodes.json
                kubectl -n {{ .Release.Namespace }} create configmap besu-node-enodes --from-file=static-nodes.json=/tmp/static-nodes.json -o yaml --dry-run=client | kubectl replace -f -
              }

              function update_tessera_peers_configmap {
                kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o json
                # first time a tx node is deployed and there is no configmap
                if [ $? -ne 0 ]; then
                  echo "No tessera-peers found, creating a new one..."
                  echo "[{ \"url\": \"http://{{ template "besu-node.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:9000\" }]"  > /tmp/tessera-peers
                  kubectl --namespace {{ .Release.Namespace }} create configmap tessera-peers --from-file=tesseraPeers=/tmp/tessera-peers

                # update the entries
                else
                  echo "Tessera-peers found, updating existing..."
                  echo $(kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o jsonpath='{.data.tesseraPeers}' ) > /tmp/tessera-peers.raw
                  NEEDLE="http://{{ template "besu-node.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:9000"
                  cat /tmp/tessera-peers.raw | jq --arg NEEDLE "$NEEDLE" '. += [{"url": $NEEDLE}] | unique ' > /tmp/tessera-peers
                  kubectl -n {{ .Release.Namespace }} create configmap tessera-peers --from-file=tesseraPeers=/tmp/tessera-peers -o yaml --dry-run=client | kubectl replace -f -
                fi
              }

{{- if and (eq .Values.provider "azure") (eq .Values.cloudSecretsStore true) }}
              function safeWriteSecret {
                key=$1
                fpath=$2
                az keyvault secret show --vault-name {{ .Values.azure.keyvaultName }} --name $key > /dev/null 2>&1
                if [ $? -ne 0 ]; then
                  az keyvault secret set --vault-name {{ .Values.azure.keyvaultName }} --name $key --file $fpath --encoding utf-8
                else
                  # if the key exists pull it from keyvault so that when you update the enodes configmap, you have the right value
                  az keyvault secret show --vault-name {{ .Values.azure.keyvaultName }} --name $key | jq -r '.value' > $fpath
                fi
              }

              az login --identity --debug
              az account set --subscription {{ .Values.azure.subscriptionId }}

{{- else if and (eq .Values.provider "aws") (eq .Values.cloudSecretsStore true) }}
              function safeWriteSecret {
                key=$1
                fpath=$2
                aws secretsmanager describe-secret --secret-id $key > /dev/null 2>&1
                if [ $? -ne 0 ]; then
                  aws secretsmanager create-secret --name $key --description $key --secret-string file://$fpath
                else
                  # if the key exists pull it from keyvault so that when you update the enodes configmap, you have the right value
                  aws secretsmanager get-secret-value --secret-id $key | jq -r '.SecretString' > $fpath
                fi
              }
{{- end }}

              echo "{{ template "besu-node.fullname" . }} hook ..."
{{- if .Values.nodeFlags.generateKeys }}       

              echo "Nodekey generation ..."
              # /opt/besu/bin/besu public-key export --to=public.key
              FOLDER_PATH=$(npx --yes --quiet quorum-genesis-tool@latest --validators 0 --members 1 --bootnodes 0 --outputPath /generated-config | tail -1 | sed -e "s/^Artifacts in folder: //")
              echo "Creating {{ template "besu-node.fullname" . }} secrets in k8s ..."
{{- if eq .Values.cloudSecretsStore true }}
              echo "Creating keys in vault for {{ template "besu-node.fullname" . }} ..."
              safeWriteSecret {{ template "besu-node.fullname" . }}-nodekey $FOLDER_PATH/member0/nodekey
              safeWriteSecret {{ template "besu-node.fullname" . }}-nodekeypub $FOLDER_PATH/member0/nodekey.pub
              safeWriteSecret {{ template "besu-node.fullname" . }}-enode $FOLDER_PATH/member0/nodekey.pub
{{- else }}
              kubectl create secret generic {{ template "besu-node.fullname" . }}-keys --namespace {{ .Release.Namespace }} --from-file=private.key=$FOLDER_PATH/member0/nodekey --from-file=public.key=$FOLDER_PATH/member0/nodekey.pub --from-file=enode=$FOLDER_PATH/member0/nodekey.pub
              cat $FOLDER_PATH/member0/nodekey.pub > /tmp/enode
{{- end}}
{{- if eq .Values.cloudSecretsStore true }}
              safeWriteSecret {{ template "besu-node.fullname" . }}-account-privateKey $FOLDER_PATH/${f}/member0/accountPrivateKey 
              safeWriteSecret {{ template "besu-node.fullname" . }}-account-password $FOLDER_PATH/${f}/member0/accountPassword 
              safeWriteSecret {{ template "besu-node.fullname" . }}-account-keystore $FOLDER_PATH/${f}/member0/accountKeystore 
              safeWriteSecret {{ template "besu-node.fullname" . }}-account-address $FOLDER_PATH/${f}/member0/accountAddress 
{{- else }}
              kubectl create secret generic {{ template "besu-node.fullname" . }}-account --namespace {{ .Release.Namespace }} --from-file=accountPrivate.key=$FOLDER_PATH/member0/accountPrivateKey --from-file=accountPassword=$FOLDER_PATH/member0/accountPassword --from-file=accountKeystore=$FOLDER_PATH/member0/accountKeystore --from-file=accountAdddress=$FOLDER_PATH/member0/accountAddress
{{- end}}
              echo "Creating configmap for node address"
              kubectl create configmap {{ template "besu-node.fullname" . }}-address --from-file=address=$FOLDER_PATH/${f}/member0/address

              update_enodes_configmap
              echo "Completed"

{{- end }}


{{- if .Values.nodeFlags.privacy }}
              FOLDER_PATH=$(npx --yes quorum-genesis-tool@latest --validators 0 --members 1 --bootnodes 0 --tesseraEnabled true --tesseraPassword {{ .Values.node.tessera.password }} --outputPath /tmp/tessera | tail -1 | sed -e "s/^Artifacts in folder: //")
              if [ ! -f "$FOLDER_PATH/member0/passwordFile.txt" ]; then
                echo "" > $FOLDER_PATH/member0/passwordFile.txt
              fi
              echo "Creating {{ template "besu-node.fullname" . }}-tessera-keys secrets in k8s ..."
{{- if eq .Values.cloudSecretsStore true }}
              safeWriteSecret {{ template "besu-node.fullname" . }}-tmkey $FOLDER_PATH/member0/tessera.key
              safeWriteSecret {{ template "besu-node.fullname" . }}-tmkeypub $FOLDER_PATH/member0/tessera.pub
              safeWriteSecret {{ template "besu-node.fullname" . }}-tmpassword $FOLDER_PATH/member0/passwordFile.txt
{{- else }}
              kubectl create secret generic {{ template "besu-node.fullname" . }}-tessera-keys --namespace {{ .Release.Namespace }} --from-file=tm.key=$FOLDER_PATH/member0/tessera.key --from-file=tm.pub=$FOLDER_PATH/member0/tessera.pub --from-file=passwordFile.txt=$FOLDER_PATH/member0/passwordFile.txt
{{- end }}
              update_tessera_peers_configmap
              echo "Tessera Completed"
{{- end }}

              echo "hook completed"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "besu-node.fullname" . }}-keys-pre-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook: "pre-delete"
    helm.sh/hook-delete-policy: "hook-succeeded"
{{- if and (eq .Values.provider "azure") (eq .Values.cloudSecretsStore true) }}
  labels:
    aadpodidbinding: "{{ .Values.azure.identityName }}"
{{- end }}
spec:
  backoffLimit: 1
  completions: 1
  template:
    metadata:
      labels:
{{- if and (eq .Values.provider "azure") (eq .Values.cloudSecretsStore true) }}
        aadpodidbinding: "{{ .Values.azure.identityName }}"
{{- end }}
        app.kubernetes.io/name: {{ include "besu-node.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- if and (eq .Values.provider "azure") (eq .Values.cloudSecretsStore true) }}
      serviceAccountName: {{ include "besu-node.fullname" . }}-hooks-sa
{{- else if and (eq .Values.provider "aws") (eq .Values.cloudSecretsStore true) }}
      serviceAccountName: {{ .Values.aws.serviceAccountName }}{{- else }}
    name: {{ include "besu-genesis.name" . }}-sa
{{- else }}
      serviceAccountName: {{ include "besu-node.fullname" . }}-hooks-sa
{{- end}}
      restartPolicy: "OnFailure"
      containers:
        - name: delete-keys
          image: {{ .Values.image.hooks.repository }}:{{ .Values.image.hooks.tag }}
          securityContext:
            runAsUser: 0
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
          args:
            - |

              function delete_node_from_tessera_peers_configmap {
                kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o json
                # if there is no configmap, do nothing
                if [ $? -ne 0 ]; then
                  echo "No tessera-peers found, nothing to do..."
                # delete the one
                else
                  echo "tessera-peers found, deleting {{ template "besu-node.fullname" . }}..."
                  echo $(kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o jsonpath='{.data.tesseraPeers}' ) > /tmp/tessera-peers.raw
                  cat /tmp/tessera-peers.raw | jq --arg NEEDLE "{{ template "besu-node.fullname" . }}" 'del(.[] | select( .url | contains($NEEDLE) ))' > /tmp/tessera-peers
                  kubectl -n {{ .Release.Namespace }} create configmap tessera-peers --from-file=tesseraPeers=/tmp/tessera-peers -o yaml --dry-run=client | kubectl replace -f -
                fi
              }

              function delete_node_from_enodes_configmap {
                kubectl -n {{ .Release.Namespace }}  get configmap besu-node-enodes -o json
                # if there is no configmap, do nothing
                if [ $? -ne 0 ]; then
                  echo "No peers found, nothing to do..."
                # delete the one 
                else    
                  echo "besu-node-enodes found, deleting {{ template "besu-node.fullname" . }}..."
                  echo $(kubectl -n {{ .Release.Namespace }} get configmap besu-node-enodes -o jsonpath='{.data.static-nodes\.json}' ) > /tmp/static-nodes.json.raw
                  cat /tmp/static-nodes.json.raw | jq --arg NEEDLE "{{ template "besu-node.fullname" . }}" 'del(.[] | select( . | contains($NEEDLE) ))' > /tmp/static-nodes.json
                  kubectl -n {{ .Release.Namespace }} create configmap besu-node-enodes --from-file=static-nodes.json=/tmp/static-nodes.json -o yaml --dry-run=client | kubectl replace -f -
                fi
              }

              delete_node_from_enodes_configmap
              delete_node_from_tessera_peers_configmap

            {{- if and (.Values.nodeFlags.removeKeysOnDeletion) (eq .Values.cloudSecretsStore false) }}       

              echo "Deleting node secrets in k8s ..."
              kubectl delete secret {{ template "besu-node.fullname" . }}-keys --namespace {{ .Release.Namespace }}
              kubectl delete secret {{ template "besu-node.fullname" . }}-account --namespace {{ .Release.Namespace }}
              kubectl delete configmap {{ template "besu-node.fullname" . }}-address --namespace {{ .Release.Namespace }}

            {{- if and .Values.nodeFlags.privacy (eq .Values.cloudSecretsStore false) }}
              kubectl delete secret {{ template "besu-node.fullname" . }}-tessera-keys --namespace {{ .Release.Namespace }}

            {{- end }}

            {{- end }}
              echo "Completed"

                           
