kubectl delete -f statefulsets/validator1-statefulset.yaml
kubectl delete -f statefulsets/validator2-statefulset.yaml
kubectl delete -f statefulsets/validator3-statefulset.yaml
kubectl delete -f statefulsets/validator4-statefulset.yaml
kubectl delete -f deployments/
kubectl delete -f secrets/
kubectl delete -f configmap/
kubectl delete -f services/
kubectl delete -f namespace/